version = 0.1

[default.deploy.parameters]
stack_name = "popup-chatbot"
s3_bucket = "cpu-ai-chatbot-lambda"
s3_prefix = "popup-chatbot"
region = "ap-northeast-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []

[default.global.parameters]
region = "ap-northeast-2"
